### ISSUE TITLE
OWL Different Individuals Axiom references an anonymous individual

### ISSUE THREAD

**Issue by dillerm** [Superraptor/GSSO#8]
Speaking from experience, I'm guessing someone had jittery fingers and accidentally created a blank OWL Different Individuals Axiom while editing 'agi' (GSSO:002037) (the OWL individual, not the class). Fortunately, the fix is really easy: either delete the blank different individuals axiom in Protégé or delete the lines (261766-261772) in gsso.owl.

**Comment by dillerm** [comment]
I'm also seeing this for 'homosociality' (GSSO:007189) (again, the OWL Individual).

**Comment by Superraptor** [comment]
Hello! Thanks for the comment: actually this issue doesn't have much to do with slippery fingers or anything, but it is actually an artifact of attempting to convert an individual to a class or vice versa in Protégé. Given that I'm the sole developer on the project I've gone back in and corrected those you've mentioned (by commenting out first, as I'm not sure if changing further may effect opening the files in Protégé somehow); but I really think it would be more useful to streamline the process to convert from class to individual or vice versa in Protégé in the future (in this project oftentimes that parent class was not necessarily clear, so individuals were often used when a parent class was not yet determined as a placeholder). If you come across any other issues, please let us know, although I apologize that I may not be able to respond to them immediately.

Changes are commented out on lines 277628 (for homosociality, GSSO:007189) and 263458 (for agi, GSSO:002037), and nothing appears to be broken in Protégé at a cursory glance. Thank you so much for your interest in the project and let me know if I can provide anything for any projects you may be considering using the GSSO!

**Comment by dillerm** [comment]
Ah, I see. Are these the only two punned individuals (i.e., individuals that have the same IRI as the class they are instances of) in GSSO? I'm certain that those were the only two individuals with this issue, so I'm curious as to why it would only occur with these two if there are other punned individuals. 

Also, I deleted the axioms in my local copy of GSSO without it breaking or otherwise affecting the ontology.

**Comment by Superraptor** [comment]
I think it may be affecting some other classes/instances (like Two-Spirit), but I'm not entirely sure (it's hard to tell what is a formatting error due to the software, a manual error on my end, or a processing error of the software, so debugging can get difficult fast for a singular human being). I'm glad it's not breaking on your end! That's good to hear!

But it's really thanks to users like you that I catch these things; once the ontology expanded to more than 10,000 manually-added terms, it got a bit unwieldy. I'm still working at securing funding to keep the project in tip-top shape, but I sincerely appreciate your feedback!

**Comment by Superraptor** [comment]
Closing issue as no response for a week; please re-open if relevant!
