### ISSUE TITLE
Update license to be more appropriate for data

### ISSUE THREAD

**Issue by cthoyt** [Superraptor/GSSO#9]
Currently, this repo uses the Apache 2.0 license, which is appropriate for software, but not data. Better options for data are Creative Commons `CC BY 4.0` or `CC 0`.

Further, this ontology is in the OBO Foundry, which *sort of* requires one of those appropriate licenses. Would you consider updating the license to be one of these? CC BY 4.0 is a bit better as far as attribution whereas CC0 enables maximum reuse but doesn't require attribution, so maybe you'd want to think about CC BY 4.0

**Comment by Superraptor** [comment]
Apologies for the late response. There was a rights issue early on which the Apache license was designed for, as the project includes software (most of it offline, but still bound by the license). After looking through licenses, I have selected and applied CC BY-NC-ND 4.0 for the time being.

**Comment by matentzn** [comment]
Hey @Superraptor in order to ensure GSSO can be safely reused ND licenses are very discouraged. We have had some trouble with this with other ontologies like GENO, but moved the owner to go to CC BY 4.0. When reusing terms, you are legally speaking creating derivatives. So ND means we can't reuse GSSO. Could you consider moving to a plain CCBY 4.0 for the ontology, and keep all associated software in Apache 2?

**Comment by Superraptor** [comment]
@matentzn understood; would you mind emailing me at my academic address to discuss further? I can elaborate somewhat there (it's clair.kronk@yale.edu). 

EDIT 1: As well, to be clear, the license stipulates: "You do not have to comply with the license for elements of the material in the public domain or where your use is permitted by an applicable exception or limitation." This includes fair use and fair dealing, which would include criticism, comment, news reporting, teaching (including multiple copies for classroom use), scholarship, or research. Would there be other uses that you intend outside of these? Just curious!
